name: Run Tests and SonarCloud Analysis

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask

    - name: Run tests
      run: |
        python -m unittest discover -v

  sonarcloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask

    - name: Run SonarCloud analysis
      uses: sonarsource/sonarcloud-github-action@master
      with:
        entryPoint: sonar-scanner
        args: -Dsonar.organization=cruzechevy -Dsonar.projectKey=cruzechevy_todolist -Dsonar.projectName=todolist
        projectBaseDir: .
      env:
        pythonLocation: /opt/hostedtoolcache/Python/3.12.2/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.2/x64/lib
